include:
  - board: nice_nano
    shield: osrpey-remix
    artifact-name: osprey-remix-zmk
  - board: nice_nano
    shield: osrpey-remix_dongle
    artifact-name: osprey-remix-dongle
  - board: nice_nano
    shield: settings_reset
